# This file was generated by GoReleaser. DO NOT EDIT.
cask "awsx" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "5e2ed057ba43167fb35fc2060e47ffa1cd903e338ec38619943e06a4670b4fb2"
      url "https://github.com/davidsgoncalves/awsx/releases/download/v#{version}/awsx_Darwin_x86_64.tar.gz",
        verified: "github.com/davidsgoncalves/awsx/"
    end
    on_arm do
      sha256 "0ce5f7a5f8349b0e028e048a57157eb9c70c63b677295b5af432aa71944fe667"
      url "https://github.com/davidsgoncalves/awsx/releases/download/v#{version}/awsx_Darwin_arm64.tar.gz",
        verified: "github.com/davidsgoncalves/awsx/"
    end
  end

  on_linux do
    on_intel do
      sha256 "13ad0de9360d685f8febd30df07acda8eae91bf79ee0c07bb7251eb04569a92d"
      url "https://github.com/davidsgoncalves/awsx/releases/download/v#{version}/awsx_Linux_x86_64.tar.gz",
        verified: "github.com/davidsgoncalves/awsx/"
    end
    on_arm do
      sha256 "5950054abd357fd9e277ca647bde36c08325607186754df9f9cbcdfcbe280be0"
      url "https://github.com/davidsgoncalves/awsx/releases/download/v#{version}/awsx_Linux_arm64.tar.gz",
        verified: "github.com/davidsgoncalves/awsx/"
    end
  end

  name "awsx"
  desc "Interactive AWS login and EC2 access via SSM Session Manager"
  homepage "https://github.com/davidsgoncalves/awsx"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "session-manager-plugin",
    ],
    formula: [
      "awscli",
    ]

  binary "awsx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/awsx"]
    end
  end

  # No zap stanza required

end
