# This file was generated by GoReleaser. DO NOT EDIT.
cask "awsx" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "734a9424f40fa863b7b38f9a5ffa81e8e102fec2c57b57409b0d4478d525aebe"
      url "https://github.com/davidsgoncalves/awsx/releases/download/v#{version}/awsx_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1031279e511b06a863da36941642b562b713864c3b74781694e7274b8050f191"
      url "https://github.com/davidsgoncalves/awsx/releases/download/v#{version}/awsx_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1118a3a7f07c6b79cfa6dd716f6c9269a71da74c9a1fb6b67ebc4a3798796911"
      url "https://github.com/davidsgoncalves/awsx/releases/download/v#{version}/awsx_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "049419b7070c1f2fa794de6660b8ac78761310c8a7c24dbed9dcad93dd4ad563"
      url "https://github.com/davidsgoncalves/awsx/releases/download/v#{version}/awsx_Linux_x86_64.tar.gz"
    end
  end

  name "awsx"
  desc "Interactive AWS login and EC2 access via SSM Session Manager"
  homepage "https://github.com/davidsgoncalves/awsx"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "session-manager-plugin",
    ],
    formula: [
      "awscli",
    ]

  binary "awsx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/awsx"]
    end
  end

  # No zap stanza required
end
