# This file was generated by GoReleaser. DO NOT EDIT.
cask "awsx" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "183ee26af7af950ec8a2eb7fdabc1d6e618b461752749102b4e5b7b8e1f558be"
      url "https://github.com/davidsgoncalves/awsx/releases/download/v#{version}/awsx_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2e7e0ff5ecb1a847ca039595a149b3cd11b182015561c08b3201357394a6740e"
      url "https://github.com/davidsgoncalves/awsx/releases/download/v#{version}/awsx_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "737bfe74e8a528493c84ce7bd098d14d58ccae598056a789c170590cc7e0b0d1"
      url "https://github.com/davidsgoncalves/awsx/releases/download/v#{version}/awsx_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "52b68a8738942892a73b1ad4ac00f3afc73f16c9ffabeda1adac90f7370551bd"
      url "https://github.com/davidsgoncalves/awsx/releases/download/v#{version}/awsx_Linux_x86_64.tar.gz"
    end
  end

  name "awsx"
  desc "Interactive AWS login and EC2 access via SSM Session Manager"
  homepage "https://github.com/davidsgoncalves/awsx"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "session-manager-plugin",
    ],
    formula: [
      "awscli",
    ]

  binary "awsx"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/awsx"]
    end
  end

  # No zap stanza required
end
